Extend mock binary

diff --git a/test/bin/zfs b/test/bin/zfs
--- a/test/bin/zfs
+++ b/test/bin/zfs
@@ -2,13 +2,37 @@
 
 case $@ in
 	'list dataset')
+	echo 'NAME   USED  AVAIL  REFER  MOUNTPOINT
+data  6,99T   763G  11,5M  /dataset'
 		exit 0
 		;;
+
 	'list unkown_dataset')
+		echo "cannot open 'lol': dataset does not exist" >&2
 		exit 1
 		;;
 
 	'zfs get creation -Hpr -t snapshot dataset')
-
+		echo 'data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-13-2117	creation1502659056	-
+data/shares/jf/video/tvshow@zfs-auto-snap_daily-2017-08-14-2108	creation	1502744921	-
+data/shares/jf/video/tvshow@zfs-auto-snap_weekly-2017-08-14-2108	creation1502744929	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-14-2108	creation1502744943	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-14-2200	creation1502748006	-
+data/shares/jf/video/tvshow@zfs-auto-snap_daily-2017-08-14-2200	creation	1502748015	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-14-2300	creation1502751606	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-15-0759	creation1502783973	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-15-0800	creation1502784024	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-15-0900	creation1502787608	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-15-1858	creation1502823504	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-15-1900	creation1502823616	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-15-2000	creation1502827208	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-15-2100	creation1502830811	-
+data/shares/jf/video/tvshow@zfs-auto-snap_frequent-2017-08-15-2130	creation1502832608	-
+data/shares/jf/video/tvshow@zfs-auto-snap_frequent-2017-08-15-2145	creation1502833509	-
+data/shares/jf/video/tvshow@zfs-auto-snap_hourly-2017-08-16-2014	creation1502914495	-
+data/shares/jf/video/tvshow@zfs-auto-snap_daily-2017-08-16-2014	creation	1502914510	-
+data/shares/jf/video/tvshow@zfs-auto-snap_frequent-2017-08-16-2014	creation1502914518	-
+data/shares/jf/video/tvshow@zfs-auto-snap_frequent-2017-08-16-2015	creation1502914537	-'
+		exit 0
 		;;
 esac
